package ims.service;

import java.util.List;

import ims.model.entities.Article;
import ims.model.entities.AvoirClient;
import ims.model.entities.Avoir_Articles;
import ims.model.entities.BonCommande;
import ims.model.entities.BonLivraison;
import ims.model.entities.Boncommande_Article;
import ims.model.entities.Boncommande_Offre;
import ims.model.entities.Caisse;
import ims.model.entities.CategorieArticle;
import ims.model.entities.CategorieIISociete;
import ims.model.entities.Charge;
import ims.model.entities.Client;
import ims.model.entities.Cnss;
import ims.model.entities.Contact;
import ims.model.entities.CoordonneeBancaire;
import ims.model.entities.Departement;
import ims.model.entities.Employee;
import ims.model.entities.Facture;
import ims.model.entities.FactureFournisseur;
import ims.model.entities.Facture_Article;
import ims.model.entities.Facture_Avoir;
import ims.model.entities.Fournisseur;
import ims.model.entities.Langue;
import ims.model.entities.LicenceApplication;
import ims.model.entities.LigneCaisse;
import ims.model.entities.OrdreVirement;
import ims.model.entities.Pointage;
import ims.model.entities.PrixArticleBC;
import ims.model.entities.PrixArticlesOffre;
import ims.model.entities.ListeBoncommandeFactureOffre;
import ims.model.entities.ObjetPrix;
import ims.model.entities.Offre;
import ims.model.entities.Offre_Article;
import ims.model.entities.Pays;
import ims.model.entities.Produit;
import ims.model.entities.Projet;
import ims.model.entities.Rubrique;
import ims.model.entities.Salaires;
import ims.model.entities.Secteur;
import ims.model.entities.Stock;
import ims.model.entities.Stock_Livraison;
import ims.model.entities.Tache;
import ims.model.entities.Ticker;
import ims.model.entities.Timesheet;
import ims.model.entities.TypeArticle;
import ims.model.entities.TypeCharge;
import ims.model.entities.TypePaiement;
import ims.model.entities.TypePriorite;
import ims.model.entities.TypeTicker;
import ims.model.entities.Utilisateur;
import ims.model.entities.UtilisateurHelpDesk;
import ims.model.entities.Ville;
import ims.model.entities.years;

public interface ModelServiceJDBC {
	
	
	public int getLastNumbre(String table,String Attribute,String date);
	public int getExisteArticle(String ref);
	public int getExicteClient(String societe);
	public int getExisteFournisseur(String societe);
	public int getExisteArticleContratOrServiceInOffre(int idOffre);
	public int getexsiteoffre(String numero);
	public int getexsitefacture(String numero);
	public int getOffreClient(int idclient);
	public int gestionstock(Stock_Livraison object);
	public int livraison_facture(int factureID,int LivraisonID);
	public int UpdateOffre(Offre offre);
	public int updateBoncommande(BonCommande commande,int idfournisseur,int idclient);
	public int updatePrixBoncommande(BonCommande commande);
	public int updateOffreforAddArticle(Offre offre);
	
	
	public int insertOffre_facture(Offre offre,Facture facture);
	public int AddArticleToFacture(Facture fact,Offre_Article offreart,float coeff);
	
	public int insertFactureLivraison(int idfacture,int idlivraison);
	public int insertstocklivraison(Stock_Livraison stockliv);
	public void closeconnexion();
	public int getMaxIdSockLivraison();
	public int updateStock(Stock stock);
	public int updateClient(Client client);
	public int updateFournisseur(Fournisseur fournisseur);
	public int getExisteProduit(Produit produit);
	public int getExisteTypeArticle(TypeArticle typearticle);
	public int getExisteCategorieArticle(CategorieArticle categorie);
	public int deleteArticleToBonLivraison(Stock_Livraison stocklivraison);
	public void updateBonLivraison(BonLivraison livraison);
	public void desactiverOffre(int id);
	public void AnnulerOffre(int id, int i);
	public int updateprixfacture(Facture facture);
	public int updatefacture(Facture facture);
	public void updatePrixOffre(Offre calcule);
	public void deleteOffre_Facture(String string, int id);
	public boolean deleteArtilceToBoncommande(Boncommande_Article ligne);
	public int updateArticle(Article article);
	public void retourstock(int id, float qte);
	public int AddArticleToFacturecontrat(Facture facture,Facture_Article facturearticle);
	public int deleteFacture_Livraison(int id);
	public int deleteUser(Utilisateur user);
	public int updateCategorieArticle(CategorieArticle categorieArticle);
	public int updateTypeArticle(TypeArticle typeArticle);
	public int updateUser(Utilisateur utilisateur);
	public int updatePays(Pays pays);
	public years getYears(int years);
	public int UpdateCompatbiliteFacture(Facture facture);
	public int Annuler(Facture facture);
	public int Annuler(BonCommande commande);
	public List<ListeBoncommandeFactureOffre> getListeDetailFacture();
	
	public ObjetPrix gettotalPrix(Offre offre);
	public List<PrixArticlesOffre> getArticleOffre(Offre offre);
	public List<PrixArticleBC> getArticleBC(BonCommande bc);
	public ObjetPrix gettotalPrix(BonCommande bc);
	public int insertOffre_Article(Offre_Article offre_Article);
	public int insertBoncommandeArticle(Boncommande_Article boncommande_Article);
	public int insertFactureArticle(Facture_Article t);
	public boolean deleteStock(Stock stock);
	public int AddOffreToSansfactBC(Offre calcule,String typeoffre);
	public int removeOffreTosansBoncomande(Offre offre);
	public int VerifyOffreTosansBoncommande(Offre objremove);
	public int removeOffreToSansFacture(Offre offre);
	public int VerifyOffreTosansFacture(Offre tempooffre);
	public int updateFacture_Offrecontrat(int id, int idoffre);
	public int updateContact(Contact contact);
	public int UpdateCompatbiliteBC(BonCommande boncommande);
	public List<BonCommande> getNumbcForFacture(Facture facture);
	public List<Facture> getNumfactForBC(BonCommande bc);
	
	public int updateCaisse(Caisse caisse);
	public int updatePrixCaisse(Caisse caisse);
	public int updateLigneCaisse(LigneCaisse ligne);
	public boolean deleteArticleOffre(int id);
	public boolean deletDepartement(int id);
	public boolean deleteEmployee(int id);
	public int updateEmployee(Employee employee);
	public int updateDepartement(Departement dept);
	public int updateOffre_Article(Offre_Article ligne);
	public int insertFactureAvoir(int idfacture, int id);
	public int updatecnss(Cnss cnss);
	public int updatesalaires(Salaires salaire);
	public int updateTypeCharge(TypeCharge typecharge);
	public int updateCharge(Charge charge);
	public int deleteCNSS(Cnss cnss);
	public int deleteSalaire(Salaires salaire);
	public int deleteCharge(Charge charge);
	public int updateAvoir_Article(Avoir_Articles avoirarticle);
	public int updatePrixAvoirClient(AvoirClient avoirclient);
	public int deleteAvoirArticle(Avoir_Articles avoirarticle);
	public int deleteFactureAvoir(Facture_Avoir objettempo);
	public int updateAvoirClient(AvoirClient avoirclient);
	public int confirmer(Facture facttempo);
	public int update(BonCommande commande);
	public int deleteAllSalaire(OrdreVirement ordre);
	public int updateOrdre(OrdreVirement ordre);
	public int updateProduit(Produit produit);
	public int update(FactureFournisseur factf);
	public int deleteOrdre(OrdreVirement ordre);
	public int deleteContact(Contact contacttempo);
	public int deleteArticlesToFactFournisseur(FactureFournisseur factf);
	public int updateBoncommandeArticle(Boncommande_Article ligne);
	public int updateCategorieClient(CategorieIISociete categorieII);
	public int updateSecteur(Secteur secteur);
	public int updateTypePaiement(TypePaiement typepaiementtempo);
	public boolean deleteTypePaiement(TypePaiement typepaiementsupp);
	public boolean deleteTypeArticle(TypeArticle typearticle);
	public boolean deleteArticle(Article article);
	public boolean updateCoordonneeBanquaire(CoordonneeBancaire banquetempo);
	public boolean deletePays(Pays countrytempo);
	public boolean updateVille(Ville ville);
	public boolean updateLangue(Langue vlangue);
	public boolean deleteVille(Ville ville);
	public boolean updateUserHelpDesk(UtilisateurHelpDesk user);
	public boolean deleteUserHelpdesk(UtilisateurHelpDesk userhelpdesktempo);
	public boolean deleteLiceneApps(LicenceApplication licenceappstempo);
	public boolean updateTicker(Ticker tickertempo);
	public boolean getUsercle(String cle);
	public boolean FermerTicker(Ticker tickertempo);
	public boolean update(TypePriorite typeprioriteTempo);
	public boolean update(TypeTicker typetickertempo);
	public boolean deleteTypeTicker(TypeTicker typetickertempo);
	public boolean deleteTypeProriter(TypePriorite typeprioriteTempo);
	public boolean updateTache(Tache tache);
	public boolean updateProjet(Projet projet);
	public boolean updateRubrique(Rubrique rubriquetempo);
	public boolean updateTimesheet(Timesheet timesheet);
	public boolean updatePointage(Pointage pointage);
	public boolean concretiserOffre(Offre offre);
	public boolean deleteCategorieclient(CategorieIISociete categorieII);
	public boolean deleteBncommande(BonCommande commande);
	public boolean deleteBnlivraison(BonLivraison livraison);
	public boolean deleteFacture(Facture facture);
	public boolean deleteFactureFourniseur(FactureFournisseur factf);
	public boolean deleteAvoir(AvoirClient avoirclient);
	public boolean updateContactFournisseur(Contact contacttempo);
	public boolean deleteFacture_Livraisonbyfacture(int id);
	public int getNombreFactFournisseurByFournisseur(Fournisseur fournisseur);
	public List<Article> getCountMaxAchat();
	public int getCountFactureConstater();
	public int getCountFactureNonconstater();
	public boolean deleteProduit(Produit produit);
	public boolean delete(Secteur secteurtempo);
	public boolean delete(Fournisseur fournisseur);
	public int getCaisseForMonth(String string);
	public boolean deleteArticleToFacture(Facture_Article facturearticle);
	public boolean insertFactureOffre(int FactureID, int OffreID);
	public boolean insertBCSansOffre(BonCommande commande);
	public int getIDLastCaisse();
	public List<LigneCaisse> getLigneCaisse(String choixmois, int year);
	public double getSommeCaisseEntrer();
	public double getSommeCaisseSortie();
	public Offre updateAllPrixMarge(double appmargetotal, Offre calcule);
	public boolean updateObjectif(int i);
	public boolean updateEtatOffre(Offre calcule);
	public boolean factureeOffre(Offre offre);
	public boolean contratOffre(Offre offre);
	public int VerifyOffreTosansFactureforAdd(Offre tempooffre);
	public boolean factureeCommande(BonCommande commande);
	public boolean Encourscommande(BonCommande commandeModifier,
			FactureFournisseur factf);
	public boolean constaterBonCommande(BonCommande commandefournissuer);
	public boolean NonconstaterBonCommande(BonCommande commandefournissuer);
	
	public boolean updateclassementRubrique(int rubriqueID);
	public boolean insertBC_Offre(Boncommande_Offre bn);
	public boolean updateContactPrincipalForClient(Contact contacttempo);
	
}
